
// automatically generated by m4 from headers in proto subdir


/*
 * WYZ Tracker Library
 */

#ifndef __SOUND_AYWYZ_H__
#define __SOUND_AYWYZ_H__

typedef struct {
	void  *effect_table;
	void  *instrument_table;
	void  *note_table;
        void  *song_table;
} wyz_song;


extern void __LIB__ ay_wyz_init(wyz_song *) __smallc __z88dk_fastcall;


extern void __LIB__ ay_wyz_play(void) __smallc;


extern void __LIB__ ay_wyz_start(int) __smallc __z88dk_fastcall;


extern void __LIB__ ay_wyz_stop(void) __smallc;



// Sound effect functionality
typedef int wyz_effects;

extern void __LIB__ ay_wyz_effect_init(wyz_effects *effects) __smallc __z88dk_fastcall;


extern void __LIB__ ay_wyz_start_effect(int channel,int effect_number) __smallc;
extern void __LIB__ ay_wyz_start_effect_callee(int channel,int effect_number) __smallc __z88dk_callee;
#define ay_wyz_start_effect(a,b) ay_wyz_start_effect_callee(a,b)


extern void __LIB__ ay_wyz_stop_effect(void) __smallc;



#endif
