sudo: false

cache:
  directories:
  - ~/perl5/
  - ~/.ccache
 
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - dos2unix
            - libboost-all-dev
            - texinfo
            - texi2html
            - gdb
            - curl
      env:
         - MATRIX_EVAL="CC=gcc && CXX=g++"

before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cpanm dos2unix ccache ragel ; fi
  - cpanm --local-lib=~/perl5 local::lib App::Prove Modern::Perl Capture::Tiny Capture::Tiny::Extended Path::Tiny File::Path Template Template::Plugin::YAML Test::Differences Text::Table CPU::Z80::Assembler Test::Cmd::Common Test::HexDifferences Data::HexDump Object::Tiny::RW Regexp::Common List::Uniq Clone
  - eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

before_script:
  - export PATH=`pwd`/bin:$PATH
  - export ZCCCFG=`pwd`/lib/config
  - ulimit -c unlimited -S       # enable core 

script:
  - ./build.sh -e -t

# show backtrace on core dump - replace path to executable file and un-comment following lines
#after_failure:
#  - COREFILE=$(find . -name "core*" | head -n 1) # find core file
#  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" INSERT-EXECUTABLE-HERE -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
