/*
 * Copyright (c) 2021 DrunkFly Team
 * Licensed under 3-clause BSD license
 */
#include "engine_p.h"

#ifdef __SDCC
#pragma codeseg MYX_STARTUP
#pragma constseg MYX_STARTUP
#endif

void MYXP_PlatformInit()
{
    NEXT_SETREG(NEXT_SPRITELAYERMODE,
        NEXT_SPRITE_127_ON_TOP |
        NEXT_ORDER_LAYER2_SPRITES_ULA |
        NEXT_SPRITES_VISIBLE);

    NEXT_SETREG(NEXT_PALETTECONTROL,
        NEXT_DRAW_LAYER2_PALETTE0 |
        NEXT_DRAW_SPRITES_PALETTE0 |
        NEXT_DRAW_ULA_PALETTE0);

    NEXT_SETREG(NEXT_SPRITETRANSPARENCY, MYX_TRANSPARENT_COLOR_INDEX4);

    NEXT_SETREG(NEXT_PERIPHERALCONTROL1,
        NEXT_JOY1_MEGADRIVE1 |
        NEXT_JOY2_MEGADRIVE2 |
        NEXT_50HZ_MODE |
        (NEXT_GETREG(NEXT_PERIPHERALCONTROL1) & NEXT_ENABLE_SCANDOUBLER));

    NEXT_SETREG(NEXT_PERIPHERALCONTROL2,
        NEXT_PS2MODE_KEYBOARD |
        NEXT_AUDIOCHIP_AY);

    NEXT_SETREG(NEXT_TURBOMODE, NEXT_28MHZ);

    NEXT_SETREG(NEXT_TILEDEFINITIONSBASE, 0x00);
    NEXT_SETREG(NEXT_TILEMAPBASE, 0x20);

    NEXT_SETREG(NEXT_TILEMAPCONTROL,
        NEXT_TILEMAP_ENABLED |
        NEXT_TILEMAP_40X32 |
        NEXT_TILEMAP_HAS_ATTRIBUTES | 
        NEXT_TILEMAP_USE_PRIMARY_PALETTE |
        NEXT_TILEMAP_512_TILES |
        NEXT_TILEMAP_OVER_ULA);

    NEXT_SETREG(NEXT_LAYER2_X_OFFSET, 0);
    NEXT_SETREG(NEXT_LAYER2_Y_OFFSET, 0);
    NEXT_SETREG(NEXT_TILEMAP_X_OFFSET_LSB, 0);
    NEXT_SETREG(NEXT_TILEMAP_X_OFFSET_MSB, 0);
    NEXT_SETREG(NEXT_TILEMAP_Y_OFFSET, 0);

    NEXT_SETREG(NEXT_CLIP_WINDOW_CONTROL,
        NEXT_RESET_TILEMAP_CLIP_INDEX |
        NEXT_RESET_ULA_CLIP_INDEX |
        NEXT_RESET_SPRITE_CLIP_INDEX |
        NEXT_RESET_LAYER2_CLIP_INDEX);

    NEXT_SETREG(NEXT_CLIP_WINDOW_TILEMAP, MYX_NEXT_BORDER_SIZE/2);          // X1
    NEXT_SETREG(NEXT_CLIP_WINDOW_TILEMAP, (MYX_NEXT_BORDER_SIZE+256-1)/2);  // X2
    NEXT_SETREG(NEXT_CLIP_WINDOW_TILEMAP, MYX_NEXT_BORDER_SIZE);            // Y1
    NEXT_SETREG(NEXT_CLIP_WINDOW_TILEMAP, (byte)(MYX_NEXT_BORDER_SIZE+192-1));    // Y2

    NEXT_SETREG(NEXT_GLOBALTRANSPARENCYCOLOR, MYX_TRANSPARENT_COLOR_INDEX8);

    NEXT_SETREG(NEXT_LAYER2CONTROLREGISTER, NEXT_LAYER2_320X256_8BPP);

    NEXT_SETREG(NEXT_LAYER2BANK, ZXNEXT_LAYER2_BANK16K);
    NEXT_SETREG(NEXT_LAYER2SHADOWBANK, ZXNEXT_LAYER2SHADOW_BANK16K);

    for (byte i = 0; i < ZXNEXT_LAYER2_NUM_BANKS16K * 2; i++) {
        NEXT_SETREG(NEXT_MMUSLOT0, ZXNEXT_LAYER2_BANK16K * 2 + i);
        memset((void*)0, 0, 8192);
    }

    NEXT_Layer2AccessPort = NEXT_LAYER2_VISIBLE;
}
