/*
 * Copyright (c) 2021 DrunkFly Team
 * Licensed under 3-clause BSD license
 */
#ifndef ENGINE_ZXMEM_H
#define ENGINE_ZXMEM_H

#define ZXNEXT_MAX_MEMORY_BANK16K   47

#define ZXNEXT_LAYER2_NUM_BANKS16K  5

#define ZXNEXT_LAYER2_BANK16K       (ZXNEXT_MAX_MEMORY_BANK16K - 2 * ZXNEXT_LAYER2_NUM_BANKS16K)
#define ZXNEXT_LAYER2SHADOW_BANK16K (ZXNEXT_LAYER2_BANK16K + ZXNEXT_LAYER2_NUM_BANKS16K)

#endif
