/*
 * Copyright (c) 2021 DrunkFly Team
 * Licensed under 3-clause BSD license
 */
#include "zxnext.h"

void MYXP_PlatformInit()
{
    NEXT_SETREG(NEXT_SPRITELAYERMODE,
        NEXT_SPRITE_127_ON_TOP |
        NEXT_ORDER_SPRITES_LAYER2_ULA |
        NEXT_SPRITES_VISIBLE);

    NEXT_SETREG(NEXT_PALETTECONTROL,
        NEXT_DRAW_LAYER2_PALETTE0 |
        NEXT_DRAW_SPRITES_PALETTE0 |
        NEXT_DRAW_ULA_PALETTE0);

    NEXT_SETREG(NEXT_SPRITETRANSPARENCY, MYX_TRANSPARENT_COLOR_INDEX4);

    NEXT_SETREG(NEXT_PERIPHERALCONTROL1,
        NEXT_JOY1_MEGADRIVE1 |
        NEXT_JOY2_MEGADRIVE2 |
        NEXT_50HZ_MODE |
        (NEXT_GETREG(NEXT_PERIPHERALCONTROL1) & NEXT_ENABLE_SCANDOUBLER));

    NEXT_SETREG(NEXT_PERIPHERALCONTROL2,
        NEXT_PS2MODE_KEYBOARD |
        NEXT_AUDIOCHIP_AY);

    NEXT_SETREG(NEXT_TURBOMODE, NEXT_28MHZ);

    NEXT_SETREG(NEXT_TILEDEFINITIONSBASE, 0x00);
    NEXT_SETREG(NEXT_TILEMAPBASE, 0x20);

    NEXT_SETREG(NEXT_TILEMAPCONTROL, 0xa3); // 10100011 FIXME!!
}
