
// automatically generated by m4 from headers in proto subdir


/*
 * WYZ Tracker Library
 */

#ifndef __SOUND_AYWYZ_H__
#define __SOUND_AYWYZ_H__

typedef struct {
	void  *effect_table;
	void  *instrument_table;
	void  *note_table;
        void  *song_table;
} wyz_song;


extern void ay_wyz_init(wyz_song *);


extern void ay_wyz_play(void);


extern void ay_wyz_start(int);


extern void ay_wyz_stop(void);



// Sound effect functionality
typedef int wyz_effects;

extern void ay_wyz_effect_init(wyz_effects *effects);


extern void ay_wyz_start_effect(int channel,int effect_number);


extern void ay_wyz_stop_effect(void);



#endif
